# Generated by Django 3.0.5 on 2020-06-10 14:48

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdOfferProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Offer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.ad',),
        ),
        migrations.CreateModel(
            name='AdRequestProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Request',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.ad',),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(upload_to=core.utils.media_path, validators=[core.utils.validate_file_extension], verbose_name='Avatar'),
        ),
    ]
