# Generated by Django 3.0.5 on 2020-06-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adbyuserproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdByUserProxy',
        ),
        migrations.CreateModel(
            name='AdByUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Offer of current user',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.ad',),
        ),
    ]
