# Generated by Django 3.0.5 on 2020-06-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200611_1835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdByUserProxy',
        ),
        migrations.CreateModel(
            name='OffersByUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Offer of current user',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.ad',),
        ),
        migrations.CreateModel(
            name='RequestByUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Request of current user',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.ad',),
        ),
    ]
